### ISSUE TITLE
screen share fails when "bitdepth 10" is configured in layouts

### ISSUE THREAD

**Issue by gshearer** [hyprwm/xdg-desktop-portal-hyprland#296] opened 2024-11-07 14:34 UTC
Not sure where to place blame, could be pipewire? But removing "bitdepth 10" from my layout config fixes it.

Errors in my log:

55514:55842:1107/093216.648495:ERROR:shared_screencast_stream.cc(215)] PipeWire stream state error: no more input formats
[55514:55842:1107/093216.648525:ERROR:shared_screencast_stream.cc(178)] PipeWire remote error: no more input formats
'loop->recurse > 0' failed at ../pipewire/src/pipewire/thread-loop.c:425 pw_thread_loop_wait()
[55514:55869:1107/093219.485650:ERROR:shared_screencast_stream.cc(215)] PipeWire stream state error: no more input formats
[55514:55869:1107/093219.485668:ERROR:shared_screencast_stream.cc(178)] PipeWire remote error: no more input formats
'loop->recurse > 0' failed at ../pipewire/src/pipewire/thread-loop.c:425 pw_thread_loop_wait()
[55567:55611:1107/093223.024037:ERROR:gbm_pixmap_wayland.cc(82)] Cannot create bo with format= YUV_420_BIPLANAR and usage=SCANOUT_CPU_READ_WRITE
[55567:55611:1107/093223.024204:ERROR:gpu_channel.cc(503)] Buffer Handle is null.
[55775:11:1107/093223.024438:ERROR:shared_image_interface_proxy.cc(134)] Buffer handle is null. Not creating a mailbox from it.

**Comment by nnra6864** [comment] 2024-11-10 17:00
I am positive this is a duplicate of #270.
Thanks for providing logs tho, I didn't do that in my post and that'll certainly be useful.

**Closed as not planned** 2024-11-11 13:46 UTC
