### ISSUE TITLE
Screen sharing only works on one monitor, window sharing not at all

### ISSUE THREAD

**Issue by erahhal** [hyprwm/xdg-desktop-portal-hyprland#276] opened 2024-10-17 16:15 UTC
### System
 
NixOS unstable
Hyprland (from hyprland flake):
```

      "locked": {
        "lastModified": 1728925396,
        "narHash": "sha256-K9Ry8H/rAavxXqTn+s/B/ZexaRsDjNpeRHFCNSq47y8=",
        "ref": "refs/heads/main",
        "rev": "22b1370ae512c92d84bbcd4cff2a3f8a4496c994",
        "revCount": 5342,
        "submodules": true,
        "type": "git",
        "url": "https://github.com/hyprwm/Hyprland"
      },

```

XDPH 1.3.6 (from hyprland flake):

```
      "locked": {
        "lastModified": 1728166987,
        "narHash": "sha256-w6dVTguAn9zJ+7aPOhBQgDz8bn6YZ7b56cY8Kg5HJRI=",
        "owner": "hyprwm",
        "repo": "xdg-desktop-portal-hyprland",
        "rev": "fb9c8d665af0588bb087f97d0f673ddf0d501787",
        "type": "github"
      },
```

Lenovo X1C gen 11 with Intel Xe grahics
2 external 4k monitors

### Issue

When sharing the screen or a window using google meet in chrome, screen sharing only works consistently for the screen at 0,0. The other screen works maybe one out of ten times. Same for window sharing, which rarely works regardless of screen.

Nothing remarkable in the logs that differentiates when it works vs when it doesn't.

**Comment by Eveeifyeve** [comment] 2024-10-26 03:52
DUPE of #280.

**Closed** 2024-10-26 18:25 UTC
