### ISSUE TITLE
Screenshare picker showing twice on ozone

### ISSUE THREAD

**Issue by Mikilio** [hyprwm/xdg-desktop-portal-hyprland#80] opened 2023-09-01 03:15 UTC
This probably isn't an issue from here but I'd like to get confirmation before I move to blame chromium.

Everytime I screen share using ozone platform be it a chromium browser or electron I need to select my target twice.

This is a mild annoyance

**Comment by vaxerski** [comment] 2023-09-01 20:30
since OBS does it correctly, that sounds like a chromium issue. Firefox in some cases asks thrice as well.

**Comment by Mikilio** [comment] 2023-09-01 22:03
I will leave this open for when someone finds a workaround just for the sake of discoverabilty

**Comment by vaxerski** [comment] 2023-09-10 23:48
dupe of #11

**Closed by vaxerski** 2023-09-10 23:48 UTC
