### ISSUE TITLE
Vesktop screensharing does not work no matter the `bitdepth`

### ISSUE THREAD

**Issue by SimonBrandner** [hyprwm/xdg-desktop-portal-hyprland#275] opened 2024-10-13 08:30 UTC
#### Bug description

When I try to screen share in Vesktop, most of the time nothing happens and I see this in the logs:

```
[93951:1013/102556.821012:ERROR:egl_dmabuf.cc(608)] Failed to record frame: Error creating EGLImage - EGL_BAD_MATCH
[93951:1013/102556.821030:ERROR:shared_screencast_stream.cc(951)] Dropping DMA-BUF modifier: 72057594037927944 and trying to renegotiate stream parameters
```

#### Version info

Hyprland: `ee8116ac5dc412dce924a0163074ce7988dd0cfc`
XDPH: `fb9c8d665af0588bb087f97d0f673ddf0d501787`

**Comment by Eveeifyeve** [comment] 2024-10-18 12:30
Asked many times, Dupe of https://github.com/hyprwm/xdg-desktop-portal-hyprland/issues/270.

**Closed** 2024-10-18 22:50 UTC
