### ISSUE TITLE
Screensharing fails on NixOS

### ISSUE THREAD

**Issue by ElysaSrc** [hyprwm/xdg-desktop-portal-hyprland#9] opened 2022-12-15 15:42 UTC
When launching the screen sharing on my NixOS setups, I encounter what seems a permission issue (here with OBS)

```
info: PipeWire initialized
info: Switched to scene 'Full desktop'
info: ------------------------------------------------
info: Loaded scenes:
info: - scene 'Alone':
info:     - source: 'Image' (image_source)
info:     - source: 'Video Capture Device (V4L2)' (v4l2_input)
info: - scene 'Full desktop':
info:     - source: 'Screen Capture (PipeWire)' (pipewire-desktop-capture-source)
info:     - source: 'Video Capture Device (V4L2)' (v4l2_input)
info: ------------------------------------------------
info: [pipewire] Screencast session created
Attempted path: share/obs/obs-studio/images/overflow.png
Attempted path: /nix/store/v5dd3g0kgk8pzjdkypky19qynwil100z-obs-studio-28.1.2/share/obs/obs-studio/images/overflow.png
info: adding 21 milliseconds of audio buffering, total audio buffering is now 21 milliseconds (source: Desktop Audio)

info: [pipewire] Asking for desktop
warning: [pipewire] Failed to start screencast, denied or cancelled by user
```

I installed hyprland using flakes and NixOS, I check the module and it seems this portal is added automatically to extra portals so my guess is the setup is pretty standard and foolproof and should work out of the box, but it is not the case.

I use nixpkgs on `nixpkgs.url = github:NixOS/nixpkgs;` (unstable).

Did I miss something or is there a bug ?
I can provide more logs if you need, let me know.

**Comment by vaxerski** [comment] 2022-12-15 16:51
@fufexan

**Comment by fufexan** [comment] 2022-12-15 16:54
> `nixpkgs.url = github:NixOS/nixpkgs;` (unstable).

That's master, not unstable.

I'll check if I can reproduce with OBS, because with Firefox it works properly.

**Comment by fufexan** [comment] 2022-12-15 16:57
Okay, it also works with OBS.

Are you overriding hyprland's `nixpkgs` input? If yes, can you check whether it works if you don't?

Do you have the NixOS (and Hyprland) config available somewhere?

**Comment by fufexan** [comment] 2022-12-15 17:04
Okay.

Anything weird in `journalctl --user -eu xdg-desktop-portal-hyprland`? Do you have other portals enabled?

**Comment by fufexan** [comment] 2022-12-15 17:43
@vaxerski any idea what that means?

**Comment by fufexan** [comment] 2022-12-15 18:01
Oh in that case I'm on it.

**Comment by fufexan** [comment] 2022-12-15 18:43
Thought there was something I left unfixed while doing the proper override for xdph in the HL flake, but it seems it's all fine.

@ElysaSrc are you using hyprland with the `nvidiaPatches = true;` override flag?

**Comment by fufexan** [comment] 2022-12-15 18:55
Okay, I think I found the problem. Can you point the HL flake to this url? `github:fufexan/Hyprland/nix-stuff`.

With that, you can set `programs.hyprland.nvidiaPatches = true;` and not set the package, and you will have the same result as the snippet you posted.

This will propagate properly to xdph and hopefully fix your issue.

**Comment by xiaoxi654** [comment] 2022-12-16 19:02
> Okay, I think I found the problem. Can you point the HL flake to this url? `github:fufexan/Hyprland/nix-stuff`.
> 
> With that, you can set `programs.hyprland.nvidiaPatches = true;` and not set the package, and you will have the same result as the snippet you posted.
> 
> This will propagate properly to xdph and hopefully fix your issue.

I switched input to your fork and set `nvidiaPatches` to `true`.
If I’m not doing wrong, the issue still exists. Log is same as above.

**Comment by fufexan** [comment] 2022-12-17 17:02
@xiaoxi654 I've updated that branch, can you update the input and try again?

**Comment by xiaoxi654** [comment] 2022-12-17 19:11
> @xiaoxi654 I've updated that branch, can you update the input and try again?

Now it works, thank you!

**Comment by fufexan** [comment] 2022-12-17 19:32
Great, I'll push to main then. Thanks for testing.

**Comment by fufexan** [comment] 2022-12-17 19:45
Fixed in https://github.com/hyprwm/Hyprland/commit/e7940569dde86d92e25ceb07824f6853515ca0b5

**Closed by fufexan** 2022-12-17 19:45 UTC
